# Generated by Django 4.0.5 on 2022-06-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechAidapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='address',
            field=models.CharField(default='address', max_length=200),
        ),
        migrations.AddField(
            model_name='hospital',
            name='city',
            field=models.CharField(default='city', max_length=100),
        ),
    ]
